//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVeSo.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KetQuaSoXo
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        [Display(Name = "Mã Loại Vé Số")]
        public string MaLoaiVeSo { get; set; }
        [Display(Name = "Mã Giải")]
        public string MaGiai { get; set; }
        [Display(Name = "Ngày Sổ")]
        public Nullable<System.DateTime> NgaySo { get; set; }
        [Display(Name = "Số Trúng")]
        public string SoTrung { get; set; }
    
        public virtual Giai Giai { get; set; }
        public virtual LoaiVeso LoaiVeso { get; set; }
    }
}
