//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVeSo.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhatHanh
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        [Display(Name = "Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Mã Loại Vé Số")]
        public string MaLoaiVeSo { get; set; }
        [Display(Name = "Số Lượng Giao")]
        [DisplayFormat(DataFormatString = "{0:0,0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> SoLuong { get; set; }
        [Display(Name = "Ngày Giao")]
        public System.DateTime NgayNhan { get; set; }
        [Display(Name = "Số Lượng Bán Được")]
        public Nullable<int> SLBan { get; set; }
        [Display(Name = "Doanh Thu")]
        public Nullable<decimal> DoanhThuDPH { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hoa Hồng")]
        public Nullable<decimal> HoaHong { get; set; }
        [Display(Name = "Tiền Phải Trả")]
        public Nullable<decimal> TienThanhToan { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual LoaiVeso LoaiVeso { get; set; }
    }
}
