//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVeSo.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SoLuongDK
    {
        [Display(Name = "ID")]
        public string ID { get; set; }
        [Display(Name = "Mã Đại Lý")]
        public string MaDaiLy { get; set; }
        [Display(Name = "Ngày Đăng Ký")]
        public System.DateTime NgayDK { get; set; }
        [Display(Name = "Số Lượng")]
        public decimal SLDK { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
    }
}
